myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('remove/<product_id>/', views.CartRemove, name='CartRemove'),
    path('add/<product_id>/', views.CartAdd, name='CartAdd'),
    path('', views.CartDetail, name='CartDetail'),
]

myshop/cupons/urls.py
from django.urls import path 
from . import views

app_name = 'cupons'

urlpatterns = [
    path('apply', views.CuponApply, name='apply')
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('cupons/', include('cupons.urls', namespace='cupon')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.OrderCreate, name='OrderCreate'),
    path('admin/order/<order_id>/', views.AdminOrderDetail, name='AdminOrderDetail'),
    path('admin/order/<order_id>/pdf/', views.AdminOrderPDF, name='AdminOrderPDF')
]

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('<category_slug>/', views.ProductList, name='ProductListByCategory'),
    path('<id>/<slug>/', views.ProductDetail, name='ProductDetail'),
    path('', views.ProductList, name='ProductList'),
]

myshop/cart/forms.py
from django import forms
from shop.models import Product

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField( choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from cupons.forms import CuponApplyForm

# Create your views here.

@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('cart:CartDetail')

def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')

def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    cupon_apply_form = CuponApplyForm()
    return render(request, 'cart/detail.html',
                  {'cart': cart, 'cupon_apply_form': cupon_apply_form})

myshop/cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% block title %}
    Cart
{% endblock %}
{% block content %}
    <h1>Cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Item</th>
                <th>Quantity</th>
                <th>Delete</th>
                <th>Full price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{{ product.image.url }}" width='100' height='150' alt="" />
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url 'cart:CartAdd' product.id %}" method='POST' class='add'>
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.update }}
                                {% csrf_token %}
                                <input type="submit" value="Refresh">
                            </form>
                        </td>
                        <td><a href="{% url 'cart:CartRemove' product.id %}">Delete</a></td>
                        <td class="num">{{ item.price }} $</td>
                        <td class="num">{{ item.total_price }} $</td>
                    </tr>
                {% endwith %}
            {% endfor %}
                {% if cart.cupon  %}
                    <tr class="subtotal">
                        <td>Amount without discount</td>
                        <td colspan="4"></td>
                        <td>{{ cart.get_total_price }}</td>
                    </tr>
                    <tr>
                        <td>
                            "{{ cart.cupon.code }}" {{ cart.cupon.discount }} % discount coupon.
                        </td>
                        <td colspan="4"></td>
                        <td class="num discount">- {{ cart.get_discount|floatformat:"2" }} $</td>
                    </tr>
                {% endif %}
                <tr class="total">
                    <td>Total:</td>
                    <td colspan="4"></td>
                    <td class="num">{{ cart.get_total_price_after_discount|floatformat:"2" }} $</td>
                </tr>
        </tbody>
    </table>

    <p>Apply Discount</p>
    <form action="{% url 'cupon:apply' %}" method='post' class='add'>
        {% csrf_token %}
        {{ cupon_apply_form }}
        <input type="submit" value="Refresh">
    </form>
    <p class="text-right">
        <a href="{% url 'shop:ProductList' %}" class="btn">Continue Shopping</a>
        <a href="{% url 'orders:OrderCreate' %}" class="btn">Order formalization</a>
    </p>
{% endblock %}    