myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('remove/<product_id>/', views.CartRemove, name='CartRemove'),
    path('add/<product_id>/', views.CartAdd, name='CartAdd'),
    path('', views.CartDetail, name='CartDetail'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('cupons/', include('cupons.urls', namespace='cupon')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('<category_slug>/', views.ProductList, name='ProductListByCategory'),
    path('<id>/<slug>/', views.ProductDetail, name='ProductDetail'),
    path('', views.ProductList, name='ProductList'),
]

myshop/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

# Category model
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'    

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:ProductListByCategory", args=[self.slug])

# Product model
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products',
        verbose_name='Category', on_delete=models.PROTECT)
    name = models.CharField(max_length=200, db_index=True,
        verbose_name='Name')
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, 
        verbose_name='Item Image')
    description = models.TextField(blank=True, verbose_name='Description')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Price')
    stock = models.PositiveIntegerField(verbose_name='In stock')
    available = models.BooleanField(default=True, verbose_name='Available')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'slug']
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:ProductDetail", args=[self.id, self.slug])

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

# Create your views here.

# Page with products
def ProductList(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products
    })

# Products page
def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html',
                 {'product': product,
                  'cart_product_form': cart_product_form})

myshop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang='ru'>
<head>
    <meta charset='UTF-8'>
    <title>{% block title %}{% endblock %}</title>
    <style>
        table {
            width: 100%;
        }
        .coll {
            width: 100px;
        }
        .container {
            width: 100%;
            max-width: 960px;
            margin: 0 auto;
        }
        .gall {
            float: left;
            width: 50%;
            padding: 10px;
            box-sizing: border-box;
        }
        .gall img{
            display: block;
            max-width: 100%;
            height: 100px;
        }
        A.link1 { font-size: 24px;}
    </style>
    
    <!-- Styles -->
    <link rel='stylesheet' href='{% static 'css/bootstrap.min.css' %}'>
    <link rel='stylesheet' href='{% static 'css/style.css' %}'>
</head>
<body>
    <section id='header'>
        <div class='top container'>
            My Online-shop
        </div>
        <div class='top-bl'>
            <div class='container'>
               <a href='/' class='link1'>Home</a>
                <div class='cart'>
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            Cart:
                            <a href="{% url 'cart:CartDetail' %}">
                                {{ total_items}} prod. {{ cart.get_total_price}} $
                            </a>
                        {% else %}
                            The cart is empty
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
    </section>
    <section id='content row' class='container'>
        {% block content %}{% endblock %}
    </section>
</body>
</html>